### ISSUE TITLE
Do you have a plan to improve the expandability  of current project to generate C file from other json schema

### ISSUE THREAD

**Issue by tanyifeng** [giuseppe/libocispec#12]
Hi:
    I think this project is wonderful to generate C file from oci runtime-spec, it's simplified so many cockamamie maintenance works. 
    I try to generate C file from [image-spec/config-schema](https://github.com/opencontainers/image-spec/blob/master/schema/config-schema.json), It can not work well when we have such json schema:

```
"Entrypoint": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "null"
            }
          ]
        },
```

```
typedef struct {
}
oci_container_config_Entrypoint;
```

and the generated struct is empty, since current project do not support syntax of "oneOf", or type of "mapStringObject". 
    I want to know that do you have a plan to generate C file from  json schema of image-spec, since we have to parse json format data of image-spec.  Or improve the expandability  of current project to generate C file from other ordinary json schema.
    It will be very cool if we have a unified solution to generate C file from json schema, Thanks.

**Comment by giuseppe** [comment]
@tanyifeng I have not yet looked into image-spec (lack of time) but I'll surely try to offer guidance to anyone who will be interested to work on it before I'll have time for it.

I think the `generate.py` script can be made more generic and support more of json schema.

I think this case of anyOf can be supported quite easily, the second option can be just ignored as anyway an array can be NULL.  Are there more complex cases that we should support?

**Comment by tanyifeng** [comment]
@giuseppe Besides "oneOf", a basic type "number" is not supported, and there are some other type can find in [image-spec/def.json](https://github.com/opencontainers/image-spec/blob/master/schema/defs.json), including "mapStringObject", "uint64Pointer", "uint16Pointer". Maybe you don't have so much time to do it, I or @0x0916 can send more PR to make this project more generic if you like.

**Comment by giuseppe** [comment]
@tanyifeng sure, I'll happily accept patches to extend it

**Comment by giuseppe** [comment]
can we close this issue now after you added the support for the oci image format?

**Comment by tanyifeng** [comment]
Of course
