### ISSUE TITLE
commit missing

### ISSUE THREAD

**Issue by tanyifeng** [giuseppe/libocispec#38]
It seems that we lost commit [1ca4a9da9eddfec351dbb09f891d075e5fa4efb69](https://github.com/giuseppe/libocispec/pull/37/commits/ca4a9da9eddfec351dbb09f891d075e5fa4efb69) of PR [https://github.com/giuseppe/libocispec/pull/37](https://github.com/giuseppe/libocispec/pull/37). Do you know why?

**Comment by giuseppe** [comment]
that is strange, I used github to merge the PR.  In any case I cherry picked and applied it manually.
