### ISSUE TITLE
Maybe we can push libocispec to lxc community

### ISSUE THREAD

**Issue by tanyifeng** [giuseppe/libocispec#39]
See Issue: https://github.com/lxc/lxc/issues/1814 https://github.com/lxc/lxc/issues/1813

lxc is going to parse oci runtime-spec, can you please try to push libocispec to lxc community with its owner, take libocispec as a parse tool

maybe you have a deeper understanding of libocispec and more way to contact with them.

**Comment by giuseppe** [comment]
I added a comment and offered my help if needed.  I think I can close this issue :-)
