### ISSUE TITLE
How to parse schema with top-type 'array'

### ISSUE THREAD

**Issue by tanyifeng** [giuseppe/libocispec#43]
We have problems when parsing schema with top type `array`, such as [hyper-schema-output.json](https://github.com/json-schema-org/json-schema-spec/blob/master/hyper-schema-output.json)

 Can you give me some advice for parsing such file or push a patch as inspiration.

**Comment by giuseppe** [comment]
I'll try to get a look at it next week.  Is it used by OCI or would you like to make the parser more generic?
