### ISSUE TITLE
How about rename `sepc.{h|c}` to `oci_runtime_spec.{h/c}`

### ISSUE THREAD

**Issue by 0x0916** [giuseppe/libocispec#7]
The `libocispec` current only support `runtime-spec`, it  maybe support other oci spec(oci_images_spec.h) in future. 
also, `spec.h`  is more common and prone to conflict.

@giuseppe If you agree, I can make a PR for it.  Also welcome to other naming suggestions

**Comment by giuseppe** [comment]
@0x0916 sure, that sounds like a good idea!
